# Repo: FirelyTeam/azure-pipeline-templates
# File: build.yml

parameters:
  # Default values
  useVersionSuffix: true
  packageArtifacts: false
  pool: {}

jobs:
- job: Build
  pool: ${{ parameters.pool }}
  steps:
  - task: DotNetCoreInstaller@2 
    inputs:
      version: '2.2.107' 
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet new configfile'
    inputs: 
      command: custom
      custom: new
      arguments: nugetconfig
      
  - task: NuGetCommand@2
    displayName: 'add MyGetSource'
    inputs: 
      command: sources
      arguments: add  -name myget -Source https://www.myget.org/F/vonk/api/v2/package -configfile .\nuget.config
    
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore #4'
    inputs:
      command: restore
      nugetConfigPath: .\nuget.config
      feedsToUse: config
      externalFeedCredentials: MyGet
      
  - script: dotnet build --configuration $(buildConfiguration) --version-suffix $(build.buildNumber) /warnaserror
    displayName: 'dotnet build $(buildConfiguration) with version suffix'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'true'))

  - script: dotnet build --configuration $(buildConfiguration) /warnaserror
    displayName: 'dotnet build $(buildConfiguration)'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'false'))

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test UnitTests'
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - ${{ if eq(parameters.packageArtifacts, 'true') }}:
    - template: package.yml
      parameters:
        useVersionSuffix: ${{ parameters.useVersionSuffix }}
        