# Repo: FirelyTeam/azure-pipeline-templates
# File: build.yml

parameters:
  # Default values
  useVersionSuffix: true
  restoreDependencies: false
  nuGetServiceConnections: #required when restoreDependies = true
  nuGetSources: #required when restoreDependies = true
  packageArtifacts: false
  pool: {}

jobs:
- job: Build
  pool: ${{ parameters.pool }}
  steps:
  - task: DotNetCoreInstaller@2 
    inputs:
      version: '2.2.107' 

  - ${{ if eq(parameters.restoreDependencies, 'true') }}:
    - template: restore.yml
      parameters:
        nuGetServiceConnections: ${{ parameters.nuGetServiceConnections }}
        nuGetSources: ${{ parameters.nuGetSources }}
      
  - script: dotnet build --configuration $(buildConfiguration) --version-suffix $(build.buildNumber) /warnaserror
    displayName: 'dotnet build $(buildConfiguration) with version suffix'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'true'))

  - script: dotnet build --configuration $(buildConfiguration) /warnaserror
    displayName: 'dotnet build $(buildConfiguration)'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'false'))

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test UnitTests'
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - ${{ if eq(parameters.packageArtifacts, 'true') }}:
    - template: package.yml
      parameters:
        useVersionSuffix: ${{ parameters.useVersionSuffix }}
        