# Repo: FirelyTeam/azure-pipeline-templates
# File: deploy-plugin-package.yml

parameters:
  pool: {}
  nugetcredentials: 
  environment: 'plugin-deploy'
  name: 'Deploy_plugin_package'
  displayName: 'Deploy plugin as an NuGet Package'
  packageArtifactName: 'NuGetPackages'
  

jobs:
- deployment: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: ${{ parameters.packageArtifactName }}
              downloadPath: '$(System.ArtifactsDirectory)/NuGetArtifacts'


          - task: NuGetCommand@2
            displayName: 'Nuget push'
            inputs:
                command: push
                packagesToPush: '$(System.ArtifactsDirectory)/NuGetArtifacts/${{ parameters.packageArtifactName }}/*.nupkg'
                nuGetFeedType: external
                publishFeedCredentials: ${{ parameters.nugetcredentials }}
                verbosityPush: Normal  
