steps:

  # Package nugets
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      configuration: '$(buildConfiguration)'
      packDirectory: '$(Build.artifactStagingDirectory)/packages'
      nobuild: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: NuGet Packages'
    inputs:
      pathtoPublish: '$(Build.artifactStagingDirectory)/packages'
      artifactName: 'NuGet Packages'