parameters:
  # Default values
  useVersionSuffix: true
  versionSuffix: ''
  artifactName: 'NuGetPackages'

steps:
  - powershell: |
      [string] $versionSuffix = '${{ parameters.versionSuffix }}'
      [string] $addBuildNumber = '${{ parameters.useVersionSuffix }}'
      
       Write-Host "Add Build Number: $addBuildNumber"

      if ([string]::IsNullOrEmpty($versionSuffix) -and $addBuildNumber -eq 'true') 
      {
        Write-Host "I've arrived here"
        $versionSuffix = $env:BUILD_BUILDNUMBER
      }
      
      Write-Host "Version Suffix: $versionSuffix"
      Write-Host "##vso[task.setvariable variable=VersionSuffixPackage;]rc2"
    displayName: 'Retrieve version suffix for packaging'

  - powershell: |    
      Write-Host "Determining if version suffix should be used"
      
      [string]$useVersionSuffix = 'true'
      [string]$versionSuffix = '$(VersionSuffixPackage)'

      Write-Host "Version Suffix: $versionSuffix"

      if ([string]::IsNullOrEmpty($versionSuffix)) 
      {
        $useVersionSuffix = 'false'
      }
      
      Write-Host "Use Version Suffix: $useVersionSuffix"
      Write-Host "##vso[task.setvariable variable=UseVersionSuffix;]$useVersionSuffix"
    displayName: 'Determine version suffix use for packaging'

  # Package nugets
  - script: dotnet pack --no-build --configuration $(buildConfiguration) --version-suffix $(VersionSuffixPackage) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration) with version suffix'
    condition: and(succeeded(), eq(variables.UseVersionSuffix, 'true'))

  - script: dotnet pack --no-build --configuration $(buildConfiguration) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration)'
    condition: and(succeeded(), eq(variables.UseVersionSuffix, 'false'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(Build.artifactStagingDirectory)/packages'
      artifactName: ${{ parameters.artifactName }}