parameters:
  # Default values
  useVersionSuffix: true
  versionSuffix: ''
  artifactName: 'NuGetPackages'

steps:
  - powershell: |
      [string]$versionSuffix = '${{ parameters.versionSuffix }}'
      Write-Host "Version Suffix: $versionSuffix"
      [bool]$useVersionSuffix = ${{ parameters.useVersionSuffix }}
      if ([string]::IsNullOrEmpty($versionSuffix) -and ${{ $useVersionSuffix }} -eq $true) 
      {
        $versionSuffix = $env:BUILD_BUILDNUMBER
      }
     
      Write-Host "Version Suffix: $versionSuffix"
      Write-Host "##vso[task.setvariable variable=VersionSuffix]$versionSuffix"
    displayName: 'Retrieve version suffix'

  # Package nugets
  - script: dotnet pack --no-build --configuration $(buildConfiguration) --version-suffix $(VersionSuffix) --output $(Build.artifactStagingDirectory)/packages
    displayName: 'dotnet pack $(buildConfiguration) with version suffix'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(Build.artifactStagingDirectory)/packages'
      artifactName: ${{ parameters.artifactName }}