# Repo: FirelyTeam/azure-pipeline-templates
# File: publish-plugin.yml

parameters:
  pool: {}
  packageName:
  packageDescription: 
  
jobs:
- job: Publish_plugin
  displayName: 'Publish plugin as an Universal Package'
  dependsOn: Build
  pool: ${{ parameters.pool }}
  steps:
  - task: DotNetCoreInstaller@2 
    inputs:
      version: '2.2.107' 

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: |
       **\*.csproj
       !**\*Tests.csproj
      arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release '

  - task: UniversalPackages@0
    displayName: 'Universal publish'
    inputs:
      command: publish
      publishDirectory: '$(Build.ArtifactStagingDirectory)/plugin_output'
      vstsFeedPublish: 'Vonk.Data'
      vstsFeedPackagePublish: ${{ parameters.packageName }}
      packagePublishDescription: ${{ parameters.packageDescription }}
