# Repo: FirelyTeam/azure-pipeline-templates
# File: publish-plugin.yml

parameters:
  pool: {}
  useVersionSuffix: true
  restoreDependencies: false
  nuGetServiceConnections: #required when restoreDependies = true
  nuGetSources: #required when restoreDependies = true
  dotNetCoreVersion: '3.1.102' # can also be use with wildcards:  latest minor version of 3. , use '3.x'
  
jobs:
- job: Publish_plugin
  displayName: 'Publish plugin as an artifact'
  dependsOn: Build
  pool: ${{ parameters.pool }}
  steps:
  - task: DotNetCoreInstaller@2 
    inputs:
      version: ${{ parameters.dotNetCoreVersion }} 

  - ${{ if eq(parameters.restoreDependencies, 'true') }}:
    - template: restore.yml
      parameters:
        nuGetServiceConnections: ${{ parameters.nuGetServiceConnections }}
        nuGetSources: ${{ parameters.nuGetSources }}

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish with version suffix'
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: false
      projects: |
       **\*.csproj
       !**\*Tests.csproj
      ${{ if eq(parameters.restoreDependencies, 'true') }}:
        # dependencies have been restored in one of the previous steps
        arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release --version-suffix $(build.buildNumber) --no-restore'
      ${{ else }}:
        arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release --version-suffix $(build.buildNumber)'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'true'))
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: false
      projects: |
       **\*.csproj
       !**\*Tests.csproj
      ${{ if eq(parameters.restoreDependencies, 'true') }}:
        # dependencies have been restored in one of the previous steps
        arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release --no-restore'
      ${{ else }}:
        arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'false'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: plugin'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/plugin_output'
      ArtifactName: 'PluginArtifacts'
