# Repo: FirelyTeam/azure-pipeline-templates
# File: publish-plugin.yml

parameters:
  pool: {}
  useVersionSuffix: true
  
jobs:
- job: Publish_plugin
  displayName: 'Publish plugin as an artifact'
  dependsOn: Build
  pool: ${{ parameters.pool }}
  steps:
  - task: DotNetCoreInstaller@2 
    inputs:
      version: '2.2.107' 

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build with version suffix'
    inputs:
      projects: |
       **\*.csproj
       !**\*Tests.csproj
      arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release --version-suffix $(build.buildNumber)'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'true'))
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: |
       **\*.csproj
       !**\*Tests.csproj
      arguments: '-o $(Build.ArtifactStagingDirectory)/plugin_output -c Release'
    condition: and(succeeded(), eq('${{ parameters.useVersionSuffix }}', 'false'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: plugin'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/plugin_output'
      ArtifactName: 'PluginArtifacts'
