parameters: 
  artifactName:  # name of the artifact on Azure DevOps that contains the Zip file                         
  zipfile: # name or pattern of the zipfile to be extracted and scanned
  trivyIgnoreFile: '' # path to the trivy ignore file

jobs:
- job: scan  
  displayName: Scan binaries
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    displayName: Download ZipDeployArchive
    inputs:
      artifactName: ${{ parameters.artifactName }}   
      targetPath: '$(System.DefaultWorkingDirectory)'
  - task: ExtractFiles@1
    displayName: Extract  ${{ parameters.zipFile }}      
    inputs:
      archiveFilePatterns: ${{ parameters.zipFile }}   
      destinationFolder: $(System.DefaultWorkingDirectory)/Binaries   
      cleanDestinationFolder: true
      overwriteExistingFiles: false
  - template: ./scanWithRetryTask.yml
    parameters:
      dockerExtraArguments: "-v $(System.DefaultWorkingDirectory)/Binaries:/src"
      trivyExtraArguments: "filesystem /src"
      trivyIgnoreFile: ${{ parameters.trivyIgnoreFile }}
      displayName: Scan compiled code with Trivy
