parameters: 
  artifactName:  # name of the artifact on Azure DevOps that contains the Zip file                         
  zipfile: # name or pattern of the zipfile to be extracted and scanned
  
jobs:
- job: scan  
  displayName: Scan binaries
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    displayName: Download ZipDeployArchive
    inputs:
      artifactName: ${{ parameters.artifactName }}   
      targetPath: '$(System.DefaultWorkingDirectory)'
  - task: ExtractFiles@1
    displayName: Extract  ${{ parameters.zipFile }}      
    inputs:
      archiveFilePatterns: ${{ parameters.zipFile }}   
      destinationFolder: $(System.DefaultWorkingDirectory)/Binaries   
      cleanDestinationFolder: true
      overwriteExistingFiles: false
  - script: | 
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -v $(System.DefaultWorkingDirectory)/Binaries:/src  aquasec/trivy:latest  --exit-code 1 --format table --scanners vuln,misconfig,secret filesystem /src
    displayName: Scan compiled code with Trivy